# Generated by Django 5.2.3 on 2026-07-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_page',
            field=models.IntegerField(default=1),
        ),
    ]
